repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/crate-ci/typos
    rev: 12ffd4a04b4893ab75db66a59aaad2d996c3e982  # v1
    hooks:
      - id: typos
